config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save ? (redirect_to list_path(@list)) : (render "lists/show")
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save ? (redirect_to list_path(@list)) : (render :new)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <%= link_to "My watchlist", root_path %>
  <div>
    <%= link_to root_path do %>
      <i class="fas fa-plus"></i> New list
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Save your movie lists</h1>
  </div>
</div>
<div class="container">
  <ul>
    <% @lists.each do |list| %>
      <li>
        <%= list.name %> <%= link_to "See the details", list_path(list) %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Add a new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>Add a new list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>
<% @list.bookmarks.each do |bookmark| %>
  <div class="card-movie">
    <%= image_tag bookmark.movie.poster_url, alt: "Le Wagon", width: 200 %>
    <div class="card-movie-info">
      <div class="card-movie-header">
        <h2><%= bookmark.movie.title %></h2>
        <h2 class="card-movie-rating"> • <%= bookmark.movie.rating %> <i class="fas fa-star"></i></h2>
      </div>
      <p><%= bookmark.movie.overview %></p>
      <h2><i class="fas fa-quote-left"></i>   <%= bookmark.comment %></h2>
      <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure" } do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
<% end %>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Add a bookmark
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <div class="modal-body">
          <h3>New bookmark</h3>
          <%= f.association :movie, as: :select %>
          <%= f.input :comment %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr>
<%= link_to "Go back to the list", root_path %>